// Main Root File :


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// Note : MDB Libaray integration ...!
import 'mdb-react-ui-kit/dist/css/mdb.min.css'
import "@fortawesome/fontawesome-free/css/all.min.css"



// Testing Bootstrap ...
import "bootstrap/dist/css/bootstrap.css"




// Note : Importing req Components ...
import Navbar from '@/components/navigation/navigation';
import Footer from '@/components/footer/footer';


//  Import Styles

import "@/app/global.css"


const  RootLayout =({ children }) => {
  return (
    <html lang="en">
      <body>
        <Navbar />
        {children}
        <Footer/>
      </body>
    </html>
  );
}

export default RootLayout
